@isTest
public class methodBufferV12test {
	/*
    public static testmethod void TestMethodBufferTests()
    {
        TestMethodBufferV12.TestMe();
    }
    public static testmethod void TestMethodBufferTestO()
    {
        TestMethodBufferV12.TestMe();
    }
    public static testmethod void TestMethodBufferTestN()
    {
        TestMethodBufferV12.TestMe();
    }
    public static testmethod void TestMethodBufferTestT()
    {
        TestMethodBufferV12.TestMe();
    }
    public static testmethod void TestMethodBufferTestF()
    {
        TestMethodBufferV12.TestMe();
    }
    */
}