@isTest
public class methodBufferV13test {
    /*
    
    public static testmethod void TestMethodBufferTests()
    {
        TestMethodBufferV13.TestMe();
    }
    public static testmethod void TestMethodBufferTestO()
    {
        TestMethodBufferV13.TestMe();
    }
    public static testmethod void TestMethodBufferTestN()
    {
        TestMethodBufferV13.TestMe();
    }
    public static testmethod void TestMethodBufferTestT()
    {
        TestMethodBufferV13.TestMe();
    }
    public static testmethod void TestMethodBufferTestF()
    {
        TestMethodBufferV13.TestMe();
    }
    */
}